### ISSUE TITLE
Frage: eigenes RegEx

### ISSUE THREAD

**Issue by xantippe** [MetaModels/attribute_text#10]
sehe ich das richtig, dass es nicht möglich ist eine eigene RegEx in der Liste hinzuzufügen?
https://github.com/MetaModels/attribute_text/blob/b54393ecc15ad73159b58d0e25ee99d057726f52/src/MetaModels/Attribute/Text/BackendSubscriber.php#L49

... oder geht das doch?

**Comment by discordier** [comment]
Klar, eigenen listener mit geringerer prioritaet und fertig.

**Comment by xantippe** [comment]
o.k. - gibt es für mich weitere Anhaltspunkte, ähnliches Beispiel o.ä. für die Umsetzung?

**Comment by discordier** [comment]
```php
<?php
 
use ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\GetPropertyOptionsEvent;
 
return array
(
    GetPropertyOptionsEvent::NAME => array(
        function (GetPropertyOptionsEvent $event) {
            if (($event->getEnvironment()->getDataDefinition()->getName() !== 'tl_metamodel_dcasetting')
                || ($event->getPropertyName() !== 'rgxp')) {
                return;
            }
 
            $options = $event->getOptions();
 
            $options['myRgxp'] = 'myRgxp';
 
            $event->setOptions($options);
        },
        -1
    )
);
```

**Comment by xantippe** [comment]
Dank! - Kommt mit ins Handbuch...

**Comment by xantippe** [comment]
habe zum Test mal
https://docs.contao.org/books/api/extensions/hooks/addCustomRegexp.html
eingebaut - die autoload.php erzeugt 

und 

```$options['postal'] = 'postal';```

geändert...

dann kommt im BE
```Warning: call_user_func() expects parameter 1 to be a valid callback, no array or string given in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php on line 158```

'postal' taucht zumindest in der Liste beim Eingabefeld mit auf

**Comment by xantippe** [comment]
ein array mehr muss es sein lt xtra
```


<?php

use ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\GetPropertyOptionsEvent;

return array
(

   GetPropertyOptionsEvent::NAME => array(array(
       function (GetPropertyOptionsEvent $event) {
           if (($event->getEnvironment()->getDataDefinition()->getName() !== 'tl_metamodel_dcasetting')
               || ($event->getPropertyName() !== 'rgxp')
           ) {
               return;
           }

           $options = $event->getOptions();

           $options['postal'] = 'postal';

           $event->setOptions($options);
       },
       -1
     )
   )

);

**Comment by xantippe** [comment]
http://metamodels.readthedocs.org/de/latest/cookbook/panels/own-regex.html
