### ISSUE TITLE
HTML-Kodierung nicht schlüssig

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_text#11]
aus https://github.com/MetaModels/attribute_text/issues/4:

der Einsatz bzw. Wirkung der Checkboxen ist für mich nicht immer ganz schlüssig

In Auflistung ist
`Eingabe im BE` => `Ausgabe im HTML-Quelltext FE`

a) **keine Checkbox** gesetzt: wird umgewandelt => **o.k.**
aus `<strong>hier und da</strong>` => `&lt;strong&#62;hier und da&lt;/strong&#62;`

b) **"HTML-Inhalte erhalten"** gesetzt: wird nicht umgewandelt => **o.k.**
aus `<strong>hier und da</strong>` => `<strong>hier und da</strong>`

c) **"HTML-Tags nicht codieren."** gesetzt: wird nicht umgewandelt => **Unterschied zu b??**
aus `<strong>hier und da</strong>` => `<strong>hier und da</strong>`

d) **"HTML-Entitäten dekodieren."** gesetzt: **unklares Verhalten**
aus `<strong>hier und da</strong>` => `&lt;strong>hier und da&lt;/strong>`

MM core 2.0.0-alpha6

**Comment by discordier** [comment]
@stefanheimes kannst du das aufdroeseln und ggf. sagen wie es "richtig" sein sollte? Ich weiss es nicht mehr. :D

**Comment by discordier** [comment]
@zonky2 @stefanheimes was machen wir hiermit?

**Comment by zonky2** [comment]
Ich habe mir die Sache nochmal angesehen - hier werden lediglich die "Contao-Standard-DCA-Flags" für

* "HTML-Inhalte erhalten" => allowHtml https://docs.contao.org/books/manual/3.4/de/06-data-container-arrays/referenz.html
* "HTML-Tags nicht codieren." => preserveTags https://docs.contao.org/books/manual/3.4/de/06-data-container-arrays/referenz.html
* "HTML-Entitäten dekodieren." => decodeEntities https://github.com/contao/core/blob/c2ab106bcfb45a290fb1292e0c9b4265d4a86fd5/system/modules/core/library/Contao/StringUtil.php#L225

**Also:**
* **allowHtml** erlaubt die in den Contao-Einstellungen angegebenen Tags
* **preserveTags** erlaubt alle Tags
[dazu hatte ich mal eine Ergänzung zum Handbuch gemacht - war auch schonmal drin... "komisches 'System'"]
**=> damit ist die Frage aus Punkt drei "Unterschied zu b??" geklärt**

* **decodeEntities** sollte dann die HTML-Entities dekodieren (https://docs.contao.org/books/manual/3.4/de/06-data-container-arrays/referenz.html) - **was ggf. Contao nicht sauber erledigt** [wrong repository]
lt. Handbuch ist der Flag per default immer auf ```true```, so dass zu überlegen wäre ob man hier die Sache negiert zu "HTML-Entitäten nicht dekodieren." - m.E. soll aber mit Contao 4.x keine Umwandlung der HTML-Tags erfolgen, wenn diese in der DB gespeichert werden...

**Comment by zonky2** [comment]
nach Absprache mit @stefanheimes geschlossen

**Comment by zonky2** [comment]
FYI:
Prüftext: mein <span>Text</span> #Sonderzeichen <xy>haha</xy>

1.) nichts angeklickt:
MM 2.0: mein &lt;span&#62;Text&lt;/span&#62; &#35;Sonderzeichen &lt;xy&#62;haha&lt;/xy&#62;
MM 2.1: mein &lt;span&#62;Text&lt;/span&#62; &#35;Sonderzeichen &lt;xy&#62;haha&lt;/xy&#62;

2.) HTML erhalten - allowHtml
MM 2.0: mein <span>Text</span> #Sonderzeichen &lt;xy>haha&lt;/xy>
MM 2.1: mein <span>Text</span> #Sonderzeichen &lt;xy>haha&lt;/xy>

3.a) HTML erhalten - allowHtml + HTML-Tags nicht codieren - preserveTags
MM 2.0: mein <span>Text</span> #Sonderzeichen <xy>haha</xy>
MM 2.1: mein <span>Text</span> #Sonderzeichen <xy>haha</xy>

3.b) HTML-Tags nicht codieren - preserveTags
MM 2.0: mein <span>Text</span> #Sonderzeichen <xy>haha</xy>
MM 2.1: mein <span>Text</span> #Sonderzeichen <xy>haha</xy>

4.a) HTML erhalten - allowHtml +  HTML-Entitäten dekodieren - decodeEntities
MM 2.0: mein <span>Text</span> #Sonderzeichen &lt;xy>haha&lt;/xy>
MM 2.1: mein <span>Text</span> #Sonderzeichen &lt;xy>haha&lt;/xy>

4.b) HTML-Entitäten dekodieren - decodeEntities
MM 2.0: mein &lt;span>Text&lt;/span> #Sonderzeichen &lt;xy>haha&lt;/xy>
MM 2.1: mein &lt;span>Text&lt;/span> #Sonderzeichen &lt;xy>haha&lt;/xy>
