### ISSUE TITLE
HTML-Tags nicht möglich...

### ISSUE THREAD

**Issue by kein-nickname** [MetaModels/attribute_text#4]
Contao 3.3.3 / DEV-TNG
"HTML-Inhalte erhalten", welches in der Eingabemaske auswählbar, zeigt keine Funktion. Die Tags werden weiterhin gelöscht. Ist im Attribut Text HTML-Tags überhaupt vorgesehen, oder ist dies ein Fehler in der Anzeige?

**Comment by xantippe** [comment]
in MM 2.0.0-alpha2 kann ich Tags einfügen - siehe Sceenshots

auch mit Tag wie ```<this>...</this``` war das kein Problem

![08](https://cloud.githubusercontent.com/assets/1045318/11767691/198686aa-a1b5-11e5-84b3-f723aa37600f.jpg)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

![09](https://cloud.githubusercontent.com/assets/1045318/11767693/202b838e-a1b5-11e5-8904-95ab1552421e.jpg)

**Comment by discordier** [comment]
Irgendwie ist da aber dann die Beschreibung von @tim-bec missverstaendlich. Ich glaube das ticket gehoert dann eher nach [attribute_longtext](https://github.com/MetaModels/attribute_longtext)

**Comment by xantippe** [comment]
also - nochmal mit 'langtext" ohne Tiny probiert mit Checkbox "HTML-Inhalte erhalten"
=> ich sehe kein Problem...

![10](https://cloud.githubusercontent.com/assets/1045318/11834785/d661ef6e-a3cf-11e5-94aa-459700c4dcc4.jpg)


![11](https://cloud.githubusercontent.com/assets/1045318/11834787/dbb9ff4c-a3cf-11e5-9e6e-064080c23bff.jpg)

**Comment by xantippe** [comment]
Nachtrag:
der Einsatz bzw. Wirkung der Checkboxen ist für mich nicht immer ganz schlüssig...

a) **keine** Checkbox gesetzt
aus "<strong>hier und da</strong>" => ```[meinlangtext] => &lt;strong&#62;hier und da&lt;/strong&#62;```

b) "HTML-Inhalte erhalten" gesetzt
aus "<strong>hier und da</strong>" => ```[meinlangtext] => [meinlangtext] => <strong>hier und da</strong>```

c) "HTML-Tags nicht codieren." gesetzt
aus "<strong>hier und da</strong>" => ```[meinlangtext] => [meinlangtext] => <strong>hier und da</strong>```

d) "HTML-Entitäten dekodieren." gesetzt
aus "<strong>hier und da</strong>" => ```[meinlangtext] => [meinlangtext] => &lt;strong>hier und da&lt;/strong>```

**Comment by discordier** [comment]
Verstehe nicht so ganz was du meinst. Bitte benutze ganze Code blocks.

**Comment by xantippe** [comment]
Pos. 1: Eingabe im BE => Pos. 2: Ausgabe im FE

z.B.
a) **keine** Checkbox gesetzt
BE: Eingabe: ```<strong>hier und da</strong>``` 
=> 
FE: Ausgabe: ```[meinlangtext] => &lt;strong&#62;hier und da&lt;/strong&#62;```

**Comment by xantippe** [comment]
HTML-Tags sind möglich und schließe das Ticket - zu den Umwandlungen neues Ticket #11
